# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19937d4df5a529a99bc04c23b29a9247c647c454c9604e3fca52645d764e1ab8752b43dce79aefb13d9ffbedd8424e2109dba1fcce482679753129ca46e20710

test:
  secret_key_base: 10b47e0f080438130ee8cc6775e460740b00a4426eea76db879be3c4efb169d70c03905a6a8c5a9ff8818adf61a389518c413d934ecb59a9f04f810312956a2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
